language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t daniel-mock/docker-react -f Dockerfile.dev .

script:
#makes sure the test completes without waiting for a terminal char 
  - docker run -e CI=true daniel-mock/docker-react npm run test


